{{- if .Values.postal.smtp.certManager.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "postal.fullname" . }}-smtp
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: postal
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- range $k, $v := .Values.postal.smtp.certManager.labels }}
    {{$k}}: {{$v | quote}}
    {{- end }}
spec:
  commonName: {{ required "postal.smtp.hostname is required" .Values.postal.smtp.hostname }}
  dnsNames:
  - {{ required "postal.smtp.hostname is required" .Values.postal.smtp.hostname }}
  issuerRef:
    name: {{ required "postal.smtp.certManager.issuerName is required" .Values.postal.smtp.certManager.issuerName }}
    kind: {{ required "postal.smtp.certManager.issuerKind is required" .Values.postal.smtp.certManager.issuerKind }}
  secretName: {{ template "postal.fullname" . }}-smtp-tls
{{- end }}
